// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-tcPxTH4WAi4CzDaG4I6FL_JwIehARGA',
    appId: '1:810788020597:web:82e614d27b94044385f33c',
    messagingSenderId: '810788020597',
    projectId: 'flutter-todo-198b3',
    authDomain: 'flutter-todo-198b3.firebaseapp.com',
    storageBucket: 'flutter-todo-198b3.appspot.com',
    measurementId: 'G-K7L1MET1SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_ql3wh1F5Y6u4uIfsW2nwSXNN_7AIu8',
    appId: '1:810788020597:android:48610304496ed96b85f33c',
    messagingSenderId: '810788020597',
    projectId: 'flutter-todo-198b3',
    storageBucket: 'flutter-todo-198b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUy9wfu2Z3ZglbiE3hiJm8mkleplf81V4',
    appId: '1:810788020597:ios:37d9f9fdff65fbea85f33c',
    messagingSenderId: '810788020597',
    projectId: 'flutter-todo-198b3',
    storageBucket: 'flutter-todo-198b3.appspot.com',
    iosBundleId: 'com.example.chapter09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUy9wfu2Z3ZglbiE3hiJm8mkleplf81V4',
    appId: '1:810788020597:ios:37d9f9fdff65fbea85f33c',
    messagingSenderId: '810788020597',
    projectId: 'flutter-todo-198b3',
    storageBucket: 'flutter-todo-198b3.appspot.com',
    iosBundleId: 'com.example.chapter09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-tcPxTH4WAi4CzDaG4I6FL_JwIehARGA',
    appId: '1:810788020597:web:f3012d2c6aba1c0d85f33c',
    messagingSenderId: '810788020597',
    projectId: 'flutter-todo-198b3',
    authDomain: 'flutter-todo-198b3.firebaseapp.com',
    storageBucket: 'flutter-todo-198b3.appspot.com',
    measurementId: 'G-5F7EV5BB0E',
  );
}
